language: elixir
elixir:
  - 1.10
  - 1.9
  - 1.8
  - 1.7
otp_release:
  - 20.0
  - 21.0
  - 22.0
sudo: false # to use faster container based build environment
env:
  - MIX_ENV=test
install:
  - mix do local.hex --force, local.rebar --force
  - mix deps.get # need to explicitly get test deps, see mix.exs
  - mix compile
script:
  - mix test
# https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
matrix:
  exclude:
    - otp_release: 22.0
      elixir: 1.6
    - otp_release: 20.0
      elixir: 1.10
